### ISSUE TITLE
Build for SOA

### ISSUE THREAD

**Issue by deepakarchinnova** [Archinnova/clients#3]
@zeinazrien Need your offline support as I tried doing this but I don't have internet on my machine and the firewall in the bank is not allowing me to move forward

**Comment by deepakarchinnova** [comment]
@zeinazrien  Download the following :

1. https://downloads.gradle.org/distributions/gradle-3.4.1-bin.zip
2. https://github.com/xebialabs/xld-oracle-soa-plugin/archive/master.zip

**Follow the steps below:**

1. Unzip both of the downloaded files in a location (workspace- **C:/Users/Zeina Zrien/workspace**)
2. In Search, search for and then select: System (Control Panel)
3. Click the Advanced system settings link.
4. Click Environment Variables. In the section System Variables, find the PATH environment variable and select it. Click Edit. If the PATH environment variable does not exist, click New.
5. Make sure when you edit that the ending of the PATH value text field should end with a **; (i.e. semicolon)** 
6. Copy paste the absolute path till gradle bin folder approximately it would be **C:/Users/Zeina Zrien/workspacegradle-3.4.1-bin\gradle-3.4.1\bin**
7. Now open a command prompt and traverse to the root folder of xld-oracle-soa-plugin-master\xld-oracle-soa-plugin-master and type in  **./gradlew -PjythonInterpreter=jython xlPlugin**

This should build the plugin. 

If any errors let me know.

**Comment by zeinazrien** [comment]
![image](https://cloud.githubusercontent.com/assets/25415358/24603665/c813b14a-1872-11e7-8be7-c09cb125be5c.png)

**Comment by deepakarchinnova** [comment]
[Artifacts.zip](https://github.com/Archinnova/clients/files/908207/Artifacts.zip)
